definitions:
  employee.CreateRequest:
    properties:
      name:
        maxLength: 155
        minLength: 2
        type: string
    required:
    - name
    type: object
  idm_inner_common.Response-int64:
    properties:
      data:
        type: integer
      error:
        type: string
      success:
        type: boolean
    type: object
  idm_inner_common.Response-string:
    properties:
      data:
        type: string
      error:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  title: IDM API documentation
  version: 0.0.0
paths:
  /employees:
    post:
      consumes:
      - application/json
      description: Create a new employee.
      parameters:
      - description: Employee
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/employee.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/idm_inner_common.Response-int64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/idm_inner_common.Response-string'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/idm_inner_common.Response-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/idm_inner_common.Response-string'
      security:
      - ApiKeyAuth: []
      summary: create a new employee
      tags:
      - employee
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
